-- Oracle DDL for storing Map-AI generated report package
-- Run in Oracle schema used by ePermit integration.

CREATE TABLE BP_AI_REPORT_HEADER (
    REPORT_ID NUMBER(20) PRIMARY KEY,
    CASE_ID NUMBER(20),
    APPLICATION_NO VARCHAR2(120 CHAR) NOT NULL,
    BP_APPLICATION_ID NUMBER(20),
    AI_STATUS VARCHAR2(80 CHAR),
    AI_RECOMMENDATION VARCHAR2(200 CHAR),
    AI_CONFIDENCE_SCORE NUMBER(6,2),
    APPLICANT_NAME VARCHAR2(255 CHAR),
    APPLICANT_EMAIL VARCHAR2(255 CHAR),
    APPLICANT_PHONE VARCHAR2(80 CHAR),
    PLOT_NO VARCHAR2(120 CHAR),
    SCHEME_NAME VARCHAR2(120 CHAR),
    PHASE_NAME VARCHAR2(120 CHAR),
    BLOCK_NAME VARCHAR2(120 CHAR),
    BUILDING_PURPOSE VARCHAR2(160 CHAR),
    PLOT_AREA NUMBER(14,2),
    GROUND_COVERED_AREA NUMBER(14,2),
    TOTAL_COVERED_AREA NUMBER(14,2),
    FAR_VALUE NUMBER(14,4),
    NO_OF_FLOORS NUMBER(6),
    APPROVED_HEIGHT_FT NUMBER(10,2),
    LATITUDE NUMBER(18,10),
    LONGITUDE NUMBER(18,10),
    MAP_ADDRESS VARCHAR2(1000 CHAR),
    SITE_SIGNAL VARCHAR2(200 CHAR),
    REPORT_MARKDOWN CLOB,
    REPORT_HTML CLOB,
    REPORT_JSON CLOB,
    CREATED_ON DATE DEFAULT SYSDATE,
    UPDATED_ON DATE,
    CREATED_BY VARCHAR2(120 CHAR),
    UPDATED_BY VARCHAR2(120 CHAR)
);

CREATE INDEX IDX_BP_AI_RPT_APPNO ON BP_AI_REPORT_HEADER (APPLICATION_NO);
CREATE INDEX IDX_BP_AI_RPT_CASEID ON BP_AI_REPORT_HEADER (CASE_ID);

CREATE TABLE BP_AI_REPORT_RULE_DETAIL (
    DETAIL_ID NUMBER(20) PRIMARY KEY,
    REPORT_ID NUMBER(20) NOT NULL,
    RULE_CODE VARCHAR2(160 CHAR),
    RULE_STATUS VARCHAR2(80 CHAR),
    CLAUSE_REFERENCE VARCHAR2(255 CHAR),
    REQUIRED_VALUE VARCHAR2(255 CHAR),
    ACTUAL_VALUE VARCHAR2(255 CHAR),
    MESSAGE VARCHAR2(2000 CHAR),
    CREATED_ON DATE DEFAULT SYSDATE,
    CONSTRAINT FK_BP_AI_RPT_RULE_HDR
        FOREIGN KEY (REPORT_ID)
        REFERENCES BP_AI_REPORT_HEADER (REPORT_ID)
);

CREATE INDEX IDX_BP_AI_RPT_RULE_REPORT ON BP_AI_REPORT_RULE_DETAIL (REPORT_ID);

CREATE TABLE BP_AI_REPORT_SYNC_LOG (
    SYNC_LOG_ID NUMBER(20) PRIMARY KEY,
    REPORT_ID NUMBER(20),
    CASE_ID NUMBER(20),
    APPLICATION_NO VARCHAR2(120 CHAR),
    REQUEST_URI VARCHAR2(2000 CHAR),
    REQUEST_PAYLOAD CLOB,
    RESPONSE_CODE NUMBER(10),
    RESPONSE_BODY CLOB,
    IS_SUCCESS NUMBER(1) DEFAULT 0,
    ERROR_MESSAGE VARCHAR2(2000 CHAR),
    CREATED_ON DATE DEFAULT SYSDATE,
    CONSTRAINT FK_BP_AI_RPT_SYNC_HDR
        FOREIGN KEY (REPORT_ID)
        REFERENCES BP_AI_REPORT_HEADER (REPORT_ID)
);

CREATE SEQUENCE SEQ_BP_AI_REPORT_HEADER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BP_AI_REPORT_RULE_DETAIL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BP_AI_REPORT_SYNC_LOG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BP_AI_REPORT_HEADER_BI
BEFORE INSERT ON BP_AI_REPORT_HEADER
FOR EACH ROW
BEGIN
    IF :NEW.REPORT_ID IS NULL THEN
        SELECT SEQ_BP_AI_REPORT_HEADER.NEXTVAL INTO :NEW.REPORT_ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BP_AI_REPORT_RULE_DETAIL_BI
BEFORE INSERT ON BP_AI_REPORT_RULE_DETAIL
FOR EACH ROW
BEGIN
    IF :NEW.DETAIL_ID IS NULL THEN
        SELECT SEQ_BP_AI_REPORT_RULE_DETAIL.NEXTVAL INTO :NEW.DETAIL_ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BP_AI_REPORT_SYNC_LOG_BI
BEFORE INSERT ON BP_AI_REPORT_SYNC_LOG
FOR EACH ROW
BEGIN
    IF :NEW.SYNC_LOG_ID IS NULL THEN
        SELECT SEQ_BP_AI_REPORT_SYNC_LOG.NEXTVAL INTO :NEW.SYNC_LOG_ID FROM DUAL;
    END IF;
END;
/
